@geoserver_url={{env_geoserver_url}}
@credential={{env_credential}}
@workspace=fdp

### Retrieve style
GET {{geoserver_url}}/rest/workspaces/{{workspace}}/styles/zone_occupation_sol_vue_foret
Accept: application/xml 
Authorization: Basic {{credential}}

### Retrieve style MBSTYLE
GET {{geoserver_url}}/rest/workspaces/{{workspace}}/styles/zone_occupation_sol_vue_foret.mbstyle
Accept: application/vnd.geoserver.mbstyle+json
Authorization: Basic {{credential}}

### Retrieve style MBSTYLE No Workspace
GET {{geoserver_url}}/rest/styles/test_mbstyle_rest.mbstyle
Accept: application/vnd.geoserver.mbstyle+json
Authorization: Basic {{credential}}

### Retrieve style CSS
GET {{geoserver_url}}/rest/workspaces/{{workspace}}/styles/simplified_water_positron
Accept: application/vnd.geoserver.geocss+css
Content-Type: application/vnd.geoserver.geocss+css
Authorization: Basic {{credential}}

### No workspace
GET {{geoserver_url}}/rest/styles/line.css
Accept: application/xml
Authorization: Basic {{credential}}

### Get All styles - No workspace
GET {{geoserver_url}}/rest/styles
Accept: application/xml
Authorization: Basic {{credential}}

### Get All styles - With workspace
GET {{geoserver_url}}/rest/workspaces/{{workspace}}/styles
Accept: application/xml
Authorization: Basic {{credential}}


### Create Style
POST {{geoserver_url}}/rest/styles
Authorization: Basic {{credential}}
Content-Type: application/xml

<style><name>test_style2</name><filename>test_style.sld</filename></style>


### Create Style direct
POST {{geoserver_url}}/rest/styles
Authorization: Basic {{credential}}
Content-Type: application/vnd.ogc.sld+xml

<?xml version="1.0" encoding="utf-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
  <!--Generated by GeoCat Bridge 4.3 (based on bridgestyle 0.1)-->
  <NamedLayer>
    <Name>water-domain:test-rest</Name>
    <UserStyle>
      <Title>water-domain:test-rest</Title>
      <!-- Legend configuration -->
      <FeatureTypeStyle>
        <Rule>
          <Title>Borehole withdrawal
            <Localized lang="fr">Forage</Localized>
          </Title>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xlink:href="https://storage.googleapis.com/gbl-ist-ve-waterdomain${env}-assets/icons/Borehole.svg"/>
                <Format>image/svg</Format>
              </ExternalGraphic>
              <Opacity>1.0</Opacity>
              <Size>20.0</Size>
              <Rotation>0.0</Rotation>
            </Graphic>
          </PointSymbolizer>
        </Rule>
        <VendorOption name="inclusion">legendOnly</VendorOption>
      </FeatureTypeStyle>
      <!-- Map configuration -->
      <FeatureTypeStyle>
        <Rule>
          <Name>selected property</Name>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>selected</ogc:PropertyName>
              <ogc:Literal>true</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <Mark>
                <WellKnownName>circle</WellKnownName>
                <Fill>
                  <CssParameter name="fill">#FFFFFF</CssParameter>
                </Fill>
              </Mark>
              <Size>45.0</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
        <Rule>
          <Name>Borehole</Name>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xlink:href="https://storage.googleapis.com/gbl-ist-ve-waterdomain${env}-assets/icons/Borehole.svg"/>
                <Format>image/svg</Format>
              </ExternalGraphic>
              <Opacity>1.0</Opacity>
              <Size>40.0</Size>
              <Rotation>0.0</Rotation>
            </Graphic>
          </PointSymbolizer>
        </Rule>
       <Rule>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>25000.0</MaxScaleDenominator>
          <TextSymbolizer>
            <Label>
              <ogc:PropertyName>installation_name</ogc:PropertyName>
            </Label>
            <Font>
              <CssParameter name="font-family">TheSans Veolia</CssParameter>
              <CssParameter name="font-size">12</CssParameter>
            </Font>
            <LabelPlacement>
              <PointPlacement>
                <AnchorPoint>
                  <AnchorPointX>0.5</AnchorPointX>
                  <AnchorPointY>0.5</AnchorPointY>
                </AnchorPoint>
                <Displacement>
                  <DisplacementX>0</DisplacementX>
                  <DisplacementY>30.0</DisplacementY>
                </Displacement>
                <Rotation>0.0</Rotation>
              </PointPlacement>
            </LabelPlacement>
            <Halo>
              <Radius>3.571428571428571</Radius>
              <Fill>
                <CssParameter name="fill">#fafafa</CssParameter>
                <CssParameter name="fill-opacity">1.0</CssParameter>
              </Fill>
            </Halo>
            <Fill>
              <CssParameter name="fill">#323232</CssParameter>
            </Fill>
            <VendorOption name="autoWrap">50</VendorOption>
            <VendorOption name="group">yes</VendorOption>
          </TextSymbolizer>
        </Rule>
        <VendorOption name="inclusion">mapOnly</VendorOption>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

### Create Style MB direct
POST {{geoserver_url}}/rest/styles?raw=true
Accept: application/vnd.geoserver.mbstyle+json
Authorization: Basic {{credential}}
Content-Type: application/vnd.geoserver.mbstyle+json

{
  "version": 8,
  "name": "gold polygon",
  "layers": [
    {
      "id": "gold polygon",
      "type": "fill",
      "paint": {
        "fill-color": "#00ffff",
        "fill-outline-color": "#000000"
      }
    }
  ]
}


### Update MB Style
PUT {{geoserver_url}}/rest/styles/test_style?raw=true
Accept: application/vnd.geoserver.mbstyle+json
Authorization: Basic {{credential}}
Content-Type: application/vnd.geoserver.mbstyle+json

{
  "version": 8,
  "name": "gold polygon",
  "layers": [
    {
      "id": "gold polygon",
      "type": "fill",
      "paint": {
        "fill-color": "#00ffff",
        "fill-outline-color": "#000000"
      }
    }
  ]
}


### Update Style
PUT {{geoserver_url}}/rest/styles/test_style
Accept: application/vnd.ogc.sld+xml
Authorization: Basic {{credential}}
Content-Type: application/vnd.ogc.sld+xml

<?xml version="1.0" encoding="utf-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
  <!--Generated by GeoCat Bridge 4.3 (based on bridgestyle 0.1)-->
  <NamedLayer>
    <Name>water-domain:test-rest</Name>
    <UserStyle>
      <Title>water-domain:test-rest</Title>
      <!-- Legend configuration -->
      <FeatureTypeStyle>
        <Rule>
          <Title>Borehole withdrawal
            <Localized lang="fr">Forage</Localized>
          </Title>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xlink:href="https://storage.googleapis.com/gbl-ist-ve-waterdomain${env}-assets/icons/Borehole.svg"/>
                <Format>image/svg</Format>
              </ExternalGraphic>
              <Opacity>1.0</Opacity>
              <Size>20.0</Size>
              <Rotation>0.0</Rotation>
            </Graphic>
          </PointSymbolizer>
        </Rule>
        <VendorOption name="inclusion">legendOnly</VendorOption>
      </FeatureTypeStyle>
      <!-- Map configuration -->
      <FeatureTypeStyle>
        <Rule>
          <Name>selected property</Name>
          <ogc:Filter>
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>selected</ogc:PropertyName>
              <ogc:Literal>true</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <Mark>
                <WellKnownName>circle</WellKnownName>
                <Fill>
                  <CssParameter name="fill">#FFFFFF</CssParameter>
                </Fill>
              </Mark>
              <Size>45.0</Size>
            </Graphic>
          </PointSymbolizer>
        </Rule>
        <Rule>
          <Name>Borehole</Name>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>10000000.0</MaxScaleDenominator>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xlink:type="simple" xlink:href="https://storage.googleapis.com/gbl-ist-ve-waterdomain${env}-assets/icons/Borehole.svg"/>
                <Format>image/svg</Format>
              </ExternalGraphic>
              <Opacity>1.0</Opacity>
              <Size>40.0</Size>
              <Rotation>0.0</Rotation>
            </Graphic>
          </PointSymbolizer>
        </Rule>
       <Rule>
          <MinScaleDenominator>0.0</MinScaleDenominator>
          <MaxScaleDenominator>25000.0</MaxScaleDenominator>
          <TextSymbolizer>
            <Label>
              <ogc:PropertyName>installation_name</ogc:PropertyName>
            </Label>
            <Font>
              <CssParameter name="font-family">TheSans Veolia</CssParameter>
              <CssParameter name="font-size">12</CssParameter>
            </Font>
            <LabelPlacement>
              <PointPlacement>
                <AnchorPoint>
                  <AnchorPointX>0.5</AnchorPointX>
                  <AnchorPointY>0.5</AnchorPointY>
                </AnchorPoint>
                <Displacement>
                  <DisplacementX>0</DisplacementX>
                  <DisplacementY>30.0</DisplacementY>
                </Displacement>
                <Rotation>0.0</Rotation>
              </PointPlacement>
            </LabelPlacement>
            <Halo>
              <Radius>3.571428571428571</Radius>
              <Fill>
                <CssParameter name="fill">#fafafa</CssParameter>
                <CssParameter name="fill-opacity">1.0</CssParameter>
              </Fill>
            </Halo>
            <Fill>
              <CssParameter name="fill">#323232</CssParameter>
            </Fill>
            <VendorOption name="autoWrap">50</VendorOption>
            <VendorOption name="group">yes</VendorOption>
          </TextSymbolizer>
        </Rule>
        <VendorOption name="inclusion">mapOnly</VendorOption>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

### Delete Style
DELETE {{geoserver_url}}/rest/styles/test_style
Authorization: Basic {{credential}}
Content-Type: application/xml

#### Create CSS style
POST {{geoserver_url}}/rest/styles
Authorization: Basic {{credential}}
Content-Type: application/xml

<style><name>test_style</name><filename>test_style.css</filename><format>css</format></style>

### Create MBStyle
POST {{geoserver_url}}/rest/styles
Authorization: Basic {{credential}}
Content-Type: application/xml

<style><name>test_style_json</name><filename>test_style_json.json</filename><format>toto</format></style>


#### Get all Styles
GET {{geoserver_url}}/rest/styles
Accept: application/xml
Authorization: Basic {{credential}}

#### Get CSS Style
GET {{geoserver_url}}/rest/styles/nexsis/bdcarto_sld_316_350_351_352_ZONE_REGLEMENTEE_TOURISTIQUE.sld
Authorization: Basic {{credential}}
Accept: application/vnd.ogc.se+xml
####Accept: application/vnd.geoserver.geocss+css

#### Create CSS style
POST {{geoserver_url}}/rest/styles?raw=true
Authorization: Basic {{credential}}
Accept: application/vnd.geoserver.geocss+css
Content-Type: application/vnd.geoserver.geocss+css

* {
  stroke: #000000;
  stroke-linejoin: round;
  stroke-linecap: round;
  stroke-width: 1;
}

