@geoserver_url={{env_geoserver_url}}
@credential={{env_credential}}

### List All users
GET {{geoserver_url}}/rest/security/usergroup/users
Accept: application/xml 
Authorization: Basic {{credential}}
