@geoserver_url={{env_geoserver_url}}
@credential={{env_credential}}

### Get resource on server/
GET {{geoserver_url}}/rest/resource/gwc-gs.xml
Authorization: Basic {{credential}}
Accept: application/xml

### Update resource on server
PUT {{geoserver_url}}/rest/resource/gwc/geowebcache.xml
Authorization: Basic {{credential}}
Accept: application/xml
Content-Type: application/octet-stream

<?xml version="1.0" encoding="utf-8"?>
<gwcConfiguration 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://geowebcache.org/schema/1.22.0 http://geowebcache.org/schema/1.22.0/geowebcache.xsd" 
  xmlns="http://geowebcache.org/schema/1.22.0">
  <version>1.22.0</version>
  <backendTimeout>120</backendTimeout>
  <blobStores>
    <FileBlobStore default="false">
      <id>file_blobstore</id>
      <enabled>true</enabled>
      <baseDirectory>/mnt/cache/geowebcache</baseDirectory>
      <fileSystemBlockSize>4096</fileSystemBlockSize>
    </FileBlobStore>
  </blobStores>
  <gridSets>
    <gridSet>
      <name>EPSG:3857</name>
      <description></description>
      <srs>
        <number>3857</number>
      </srs>
      <extent>
        <coords>
          <double>-2.003750834E7</double>
          <double>-2.003750834E7</double>
          <double>2.003750834E7</double>
          <double>2.003750834E7</double>
        </coords>
      </extent>
      <alignTopLeft>true</alignTopLeft>
      <scaleDenominators>
        <double>5.59082264028717E8</double>
        <double>2.79541132014358E8</double>
        <double>1.39770566007179E8</double>
        <double>6.98852830035897E7</double>
        <double>3.49426415017948E7</double>
        <double>1.74713207508974E7</double>
        <double>8735660.37544871</double>
        <double>4367830.18772435</double>
        <double>2183915.09386217</double>
        <double>1091957.54693108</double>
        <double>545978.773465544</double>
        <double>272989.386732772</double>
        <double>136494.693366386</double>
        <double>68247.346683193</double>
        <double>34123.6733415964</double>
        <double>17061.8366707982</double>
        <double>8530.91833539913</double>
        <double>4265.45916769956</double>
        <double>2132.72958384978</double>
        <double>1066.36479192489</double>
        <double>533.182395962445</double>
        <double>266.591197981222</double>
        <double>133.295598990611</double>
        <double>66.6477994953056</double>
        <double>33.3238997476528</double>
      </scaleDenominators>
      <metersPerUnit>1.0</metersPerUnit>
      <pixelSize>2.8E-4</pixelSize>
      <scaleNames>
        <string>0</string>
        <string>1</string>
        <string>2</string>
        <string>3</string>
        <string>4</string>
        <string>5</string>
        <string>6</string>
        <string>7</string>
        <string>8</string>
        <string>9</string>
        <string>10</string>
        <string>11</string>
        <string>12</string>
        <string>13</string>
        <string>14</string>
        <string>15</string>
        <string>16</string>
        <string>17</string>
        <string>18</string>
        <string>19</string>
        <string>20</string>
        <string>21</string>
        <string>22</string>
        <string>23</string>
        <string>24</string>
      </scaleNames>
      <tileHeight>256</tileHeight>
      <tileWidth>256</tileWidth>
      <yCoordinateFirst>false</yCoordinateFirst>
    </gridSet>
  </gridSets>
  <layers>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>ign_scan25</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>https://wxs.ign.fr/gjv4lmeitnl3c7dss2xmkm1c/geoportail/r/wms?SERVICE=WMS</string>
      </wmsUrl>
      <wmsLayers>SCAN25TOUR_PYR-JPEG_WLD_WM</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>true</transparent>
      <concurrency>32</concurrency>
    </wmsLayer>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>ign_orthophotos</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>http://geoserver-prod-nexsis-gsc-gateway:8080/geoserver/wms?</string>
      </wmsUrl>
      <wmsLayers>ign:ORTHOIMAGERY.ORTHOPHOTOS</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>true</transparent>
      <concurrency>32</concurrency>
    </wmsLayer>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>ign_plan_ign</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>http://geoserver-prod-nexsis-gsc-gateway:8080/geoserver/wms?</string>
      </wmsUrl>
      <wmsLayers>ign:plan_ign</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>true</transparent>
      <concurrency>32</concurrency>
    </wmsLayer>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>nexsis_fdp_osm_positron</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>http://geoserver-prod-nexsis-gsc-gateway:8080/geoserver/wms?</string>
      </wmsUrl>
      <wmsLayers>osm:fdp_positron</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>true</transparent>
      <concurrency>32</concurrency>
    </wmsLayer>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>nexsis_fdp_nexsis</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>http://geoserver-prod-nexsis-gsc-gateway:8080/geoserver/wms?</string>
      </wmsUrl>
      <wmsLayers>fdp:nexsis_fdp_normal</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>false</transparent>
      <bgColor>0xAAD5E9</bgColor>
      <concurrency>32</concurrency>
    </wmsLayer>
    <wmsLayer>
      <blobStoreId>file_blobstore</blobStoreId>
      <enabled>true</enabled>
      <name>nexsis_fdp_osm</name>
      <mimeFormats>
        <string>image/png</string>
        <string>image/jpeg</string>
      </mimeFormats>
      <gridSubsets>
        <gridSubset>
          <gridSetName>EPSG:3857</gridSetName>
        </gridSubset>
      </gridSubsets>
      <metaWidthHeight>
        <int>10</int>
        <int>10</int>
      </metaWidthHeight>
      <expireCache>0</expireCache>
      <expireCacheList>
        <expirationRule minZoom="0" expiration="0"/>
      </expireCacheList>
      <expireClients>3600</expireClients>
      <expireClientsList>
        <expirationRule minZoom="0" expiration="3600"/>
      </expireClientsList>
      <backendTimeout>120</backendTimeout>
      <cacheBypassAllowed>false</cacheBypassAllowed>
      <wmsUrl>
        <string>http://geoserver-prod-nexsis-gsc-gateway:8080/geoserver/wms?</string>
      </wmsUrl>
      <wmsLayers>osm:fdp_normal</wmsLayers>
      <gutter>0</gutter>
      <wmsVersion>1.3.0</wmsVersion>
      <transparent>true</transparent>
      <concurrency>32</concurrency>
    </wmsLayer>
  </layers>
</gwcConfiguration>

### Create resource on server
PUT {{geoserver_url}}/rest/resource/pregeneralized.xml
Authorization: Basic {{credential}}
Accept: application/xml
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<GeneralizationInfos version="1.0" dataSourceNameSpace="osm" dataSourceName="osm">
  <!-- ROADS -->
  <GeneralizationInfo featureName="roads" baseFeatureName="osm_roads" geomPropertyName="geometry">
    <Generalization distance="450" featureName="osm_roads_gen1" geomPropertyName="geometry" />
    <Generalization distance="300" featureName="osm_roads_gen2" geomPropertyName="geometry" />
    <Generalization distance="30" featureName="osm_roads_gen3" geomPropertyName="geometry" />
  </GeneralizationInfo>
  <!-- LAND USAGES -->
  <GeneralizationInfo featureName="landusages" baseFeatureName="osm_landusages" geomPropertyName="geometry">
    <Generalization distance="2000" featureName="osm_landusages_gen0" geomPropertyName="geometry" />
    <Generalization distance="1000" featureName="osm_landusages_gen1" geomPropertyName="geometry" />
    <Generalization distance="500" featureName="osm_landusages_gen2" geomPropertyName="geometry" />
    <Generalization distance="125" featureName="osm_landusages_gen3" geomPropertyName="geometry" />
  </GeneralizationInfo>
  <!-- WATER AREAS -->
  <GeneralizationInfo featureName="waterareas" baseFeatureName="osm_waterareas" geomPropertyName="geometry">
    <Generalization distance="200" featureName="osm_waterareas_gen0" geomPropertyName="geometry" />
    <Generalization distance="50" featureName="osm_waterareas_gen1" geomPropertyName="geometry" />
  </GeneralizationInfo>
  <!-- WATER WAYS -->
  <GeneralizationInfo featureName="waterways" baseFeatureName="osm_waterways" geomPropertyName="geometry">
    <Generalization distance="120" featureName="osm_waterways_gen0" geomPropertyName="geometry" />
    <Generalization distance="60" featureName="osm_waterways_gen1" geomPropertyName="geometry" />
  </GeneralizationInfo>
</GeneralizationInfos>
